# ********RoostGPT********

# Test generated by RoostGPT for test karate-test using AI Type Open AI and AI Model gpt-4-turbo
# 
# Feature file generated for /listener/configurationResultEvent_post for http method type POST 
# RoostTestHash=51f5770c5e
# 
# 

# ********RoostGPT********
Feature: Testing Configuration Result Event API

  Background:
    * def urlBase = karate.properties['url.base'] || karate.get('urlBase', 'http://localhost:4010')
    * url urlBase
    * def authToken = karate.properties['AUTH_TOKEN']
    * header Authorization = 'Bearer ' + authToken

  Scenario Outline: Test Configuration Result Event with different states and types
    Given path '/listener/configurationResultEvent'
    And request
      """
      <payload>
      """
    When method POST
    Then status <expectedStatus>
    And match response == <expectedResponse>

    Examples:
      | read('listener_configurationResultEvent_post.csv') |
